development:
  clients:
    default:
      database: ppk_server
      hosts:
        - 127.0.0.1:27017
      options:
          raise_not_found_error: false
  options:
      raise_not_found_error: false
test:
  clients:
    default:
      database: ppk_server_test
      hosts:
        - 127.0.0.1:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0
